// <auto-generated />
using System;
using Infrastructure.Persistence.logistics_db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.logistics_db.Migrations
{
    [DbContext(typeof(LogisticsDbContext))]
    [Migration("20260803203119_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "attachment_type", new[] { "invoice", "payment_proof", "package_photo", "delivery_evidence", "other" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "customer_type", new[] { "individual", "online_store", "courier", "entrepreneur" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "package_status", new[] { "registered", "warehouse", "shipped", "customs", "agency", "available_pickup", "out_for_delivery", "delivered", "incident", "retained", "pending_payment" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "package_type", new[] { "standard", "fragile" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_method", new[] { "bank_transfer", "card", "credit" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_status", new[] { "pending", "validated", "rejected" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Logistics.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6)
                        .HasColumnType("timestamp(6) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_url");

                    b.Property<string>("MimeType")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("mime_type");

                    b.Property<string>("OriginalName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("original_name");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UploadedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id")
                        .HasName("attachment_pkey");

                    b.HasIndex(new[] { "PackageId" }, "idx_attachment_package");

                    b.ToTable("attachment", (string)null);
                });

            modelBuilder.Entity("Domain.Logistics.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_user_id");

                    b.Property<string>("BusinessName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("business_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6)
                        .HasColumnType("timestamp(6) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CustomerType")
                        .HasColumnType("integer");

                    b.Property<string>("DocumentId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("document_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6)
                        .HasColumnType("timestamp(6) with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Whatsapp")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("whatsapp");

                    b.HasKey("Id")
                        .HasName("customer_pkey");

                    b.HasIndex(new[] { "AppUserId" }, "customer_app_user_id_key")
                        .IsUnique();

                    b.HasIndex(new[] { "AppUserId" }, "idx_customer_app_user");

                    b.ToTable("customer", (string)null);
                });

            modelBuilder.Entity("Domain.Logistics.Entities.CustomsCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6)
                        .HasColumnType("timestamp(6) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency")
                        .HasDefaultValueSql("'USD'::character varying");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<decimal?>("MaxDeclaredValue")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("max_declared_value");

                    b.Property<decimal?>("MaxWeightKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("max_weight_kg");

                    b.Property<decimal?>("MaxWeightLb")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("max_weight_lb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6)
                        .HasColumnType("timestamp(6) with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("customs_category_pkey");

                    b.HasIndex(new[] { "Code" }, "customs_category_code_key")
                        .IsUnique();

                    b.ToTable("customs_category", (string)null);
                });

            modelBuilder.Entity("Domain.Logistics.Entities.DeclaredPurchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6)
                        .HasColumnType("timestamp(6) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency")
                        .HasDefaultValueSql("'USD'::character varying");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("CustomsCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("customs_category_id");

                    b.Property<decimal>("DeclaredValue")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("declared_value");

                    b.Property<decimal?>("EstimatedWeightLb")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("estimated_weight_lb");

                    b.Property<string>("ExternalTracking")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("external_tracking");

                    b.Property<Guid>("InvoiceAttachmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_attachment_id");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("product_description");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("store_name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6)
                        .HasColumnType("timestamp(6) with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("declared_purchase_pkey");

                    b.HasIndex("CustomsCategoryId");

                    b.HasIndex("InvoiceAttachmentId");

                    b.HasIndex(new[] { "CustomerId" }, "idx_declared_purchase_customer");

                    b.ToTable("declared_purchase", (string)null);
                });

            modelBuilder.Entity("Domain.Logistics.Entities.Locker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("City")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("city")
                        .HasDefaultValueSql("'Hialeah'::character varying");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("country")
                        .HasDefaultValueSql("'USA'::character varying");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6)
                        .HasColumnType("timestamp(6) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("state")
                        .HasDefaultValueSql("'FL'::character varying");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6)
                        .HasColumnType("timestamp(6) with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UsAddressLine")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("us_address_line");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("zip_code");

                    b.HasKey("Id")
                        .HasName("locker_pkey");

                    b.HasIndex(new[] { "Code" }, "locker_code_key")
                        .IsUnique();

                    b.HasIndex(new[] { "CustomerId" }, "locker_customer_id_key")
                        .IsUnique();

                    b.ToTable("locker", (string)null);
                });

            modelBuilder.Entity("Domain.Logistics.Entities.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6)
                        .HasColumnType("timestamp(6) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency")
                        .HasDefaultValueSql("'USD'::character varying");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("CustomsCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("customs_category_id");

                    b.Property<Guid>("DeclaredPurchaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("declared_purchase_id");

                    b.Property<decimal?>("DeclaredValue")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("declared_value");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("ExternalTracking")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("external_tracking");

                    b.Property<bool>("IsFragile")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fragile");

                    b.Property<bool>("IsRepacked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_repacked");

                    b.Property<Guid>("LockerId")
                        .HasColumnType("uuid")
                        .HasColumnName("locker_id");

                    b.Property<string>("Observations")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observations");

                    b.Property<int>("PackageType")
                        .HasColumnType("integer");

                    b.Property<int>("Pieces")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("pieces");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasPrecision(6)
                        .HasColumnType("timestamp(6) with time zone")
                        .HasColumnName("received_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6)
                        .HasColumnType("timestamp(6) with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("WarehouseNumber")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("warehouse_number");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("weight_kg");

                    b.Property<decimal?>("WeightLb")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("weight_lb");

                    b.HasKey("Id")
                        .HasName("package_pkey");

                    b.HasIndex("CustomsCategoryId");

                    b.HasIndex("DeclaredPurchaseId");

                    b.HasIndex("LockerId");

                    b.HasIndex(new[] { "CustomerId" }, "idx_package_customer");

                    b.HasIndex(new[] { "ExternalTracking" }, "idx_package_external_tracking");

                    b.HasIndex(new[] { "WarehouseNumber" }, "idx_package_warehouse_number");

                    b.HasIndex(new[] { "WarehouseNumber" }, "package_warehouse_number_key")
                        .IsUnique();

                    b.ToTable("package", (string)null);
                });

            modelBuilder.Entity("Domain.Logistics.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Code")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6)
                        .HasColumnType("timestamp(6) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency")
                        .HasDefaultValueSql("'USD'::character varying");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<int>("Method")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProofAttachmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("proof_attachment_id");

                    b.Property<string>("Reference")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("reference");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("reject_reason");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6)
                        .HasColumnType("timestamp(6) with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("ValidatedAt")
                        .HasPrecision(6)
                        .HasColumnType("timestamp(6) with time zone")
                        .HasColumnName("validated_at");

                    b.Property<Guid?>("ValidatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("validated_by");

                    b.HasKey("Id")
                        .HasName("payment_pkey");

                    b.HasIndex("ProofAttachmentId");

                    b.HasIndex(new[] { "CustomerId" }, "idx_payment_customer");

                    b.HasIndex(new[] { "Code" }, "payment_code_key")
                        .IsUnique();

                    b.ToTable("payment", (string)null);
                });

            modelBuilder.Entity("Domain.Logistics.Entities.TrackingEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6)
                        .HasColumnType("timestamp(6) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsVisibleToCustomer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_visible_to_customer");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("note");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("tracking_event_pkey");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_tracking_event_created");

                    b.HasIndex(new[] { "PackageId" }, "idx_tracking_event_package");

                    b.ToTable("tracking_event", (string)null);
                });

            modelBuilder.Entity("Domain.Logistics.Entities.Attachment", b =>
                {
                    b.HasOne("Domain.Logistics.Entities.Package", "Package")
                        .WithMany("Attachments")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("attachment_package_id_fkey");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Domain.Logistics.Entities.DeclaredPurchase", b =>
                {
                    b.HasOne("Domain.Logistics.Entities.Customer", "Customer")
                        .WithMany("DeclaredPurchases")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("declared_purchase_customer_id_fkey");

                    b.HasOne("Domain.Logistics.Entities.CustomsCategory", "CustomsCategory")
                        .WithMany("DeclaredPurchases")
                        .HasForeignKey("CustomsCategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("declared_purchase_customs_category_id_fkey");

                    b.HasOne("Domain.Logistics.Entities.Attachment", "InvoiceAttachment")
                        .WithMany("DeclaredPurchases")
                        .HasForeignKey("InvoiceAttachmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("declared_purchase_invoice_attachment_id_fkey");

                    b.Navigation("Customer");

                    b.Navigation("CustomsCategory");

                    b.Navigation("InvoiceAttachment");
                });

            modelBuilder.Entity("Domain.Logistics.Entities.Locker", b =>
                {
                    b.HasOne("Domain.Logistics.Entities.Customer", "Customer")
                        .WithOne("Locker")
                        .HasForeignKey("Domain.Logistics.Entities.Locker", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("locker_customer_id_fkey");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Domain.Logistics.Entities.Package", b =>
                {
                    b.HasOne("Domain.Logistics.Entities.Customer", "Customer")
                        .WithMany("Packages")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("package_customer_id_fkey");

                    b.HasOne("Domain.Logistics.Entities.CustomsCategory", "CustomsCategory")
                        .WithMany("Packages")
                        .HasForeignKey("CustomsCategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("package_customs_category_id_fkey");

                    b.HasOne("Domain.Logistics.Entities.DeclaredPurchase", "DeclaredPurchase")
                        .WithMany("Packages")
                        .HasForeignKey("DeclaredPurchaseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("package_declared_purchase_id_fkey");

                    b.HasOne("Domain.Logistics.Entities.Locker", "Locker")
                        .WithMany("Packages")
                        .HasForeignKey("LockerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("package_locker_id_fkey");

                    b.Navigation("Customer");

                    b.Navigation("CustomsCategory");

                    b.Navigation("DeclaredPurchase");

                    b.Navigation("Locker");
                });

            modelBuilder.Entity("Domain.Logistics.Entities.Payment", b =>
                {
                    b.HasOne("Domain.Logistics.Entities.Customer", "Customer")
                        .WithMany("Payments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("payment_customer_id_fkey");

                    b.HasOne("Domain.Logistics.Entities.Attachment", "ProofAttachment")
                        .WithMany("Payments")
                        .HasForeignKey("ProofAttachmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("payment_proof_attachment_id_fkey");

                    b.Navigation("Customer");

                    b.Navigation("ProofAttachment");
                });

            modelBuilder.Entity("Domain.Logistics.Entities.TrackingEvent", b =>
                {
                    b.HasOne("Domain.Logistics.Entities.Package", "Package")
                        .WithMany("TrackingEvents")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tracking_event_package_id_fkey");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Domain.Logistics.Entities.Attachment", b =>
                {
                    b.Navigation("DeclaredPurchases");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Domain.Logistics.Entities.Customer", b =>
                {
                    b.Navigation("DeclaredPurchases");

                    b.Navigation("Locker");

                    b.Navigation("Packages");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Domain.Logistics.Entities.CustomsCategory", b =>
                {
                    b.Navigation("DeclaredPurchases");

                    b.Navigation("Packages");
                });

            modelBuilder.Entity("Domain.Logistics.Entities.DeclaredPurchase", b =>
                {
                    b.Navigation("Packages");
                });

            modelBuilder.Entity("Domain.Logistics.Entities.Locker", b =>
                {
                    b.Navigation("Packages");
                });

            modelBuilder.Entity("Domain.Logistics.Entities.Package", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("TrackingEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
